# setup a single or list of public keys in the current users authorized_keys file
---
- name: get full path of .ssh directory
  win_shell: $env:USERPROFILE + "\.ssh"
  changed_when: False
  register: pri_openssh_ssh_dir

  # Get the SID to avoid translation issues down the line - https://github.com/jborean93/ansible-role-win_openssh/issues/11
- name: get current user SID for ACL
  win_shell: '[System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value'
  changed_when: False
  register: pri_openssh_ssh_current_user

- name: ensure the .ssh directory exists for the current user
  win_file:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}'
    state: directory

- name: set correct permissions on .ssh directory
  win_acl:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}'
    user: '{{ item }}'
    rights: FullControl
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit
    propagation: None
  with_items:
  - S-1-5-18 # "SYSTEM" group independent of localization
  - S-1-5-32-544 # "Administrators" group independent of localization
  - '{{ pri_openssh_ssh_current_user.stdout_lines[0] }}'

- name: disable ACL inheritence on .ssh directory
  win_acl_inheritance:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}'
    reorganize: False
    state: absent

- name: ensure pubkeys are added to the authorized_keys file
  win_lineinfile:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}\authorized_keys'
    create: True
    line: '{{ item }}'
    state: present
  with_items: '{{ opt_openssh_pubkeys }}'
